language: node_js
before_install:
  - curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - export PATH=/usr/local/bin:$PATH
before_script:
  - npm i -g gulp
  - npm i -g babel
script: gulp
